services:
  rss-scheduler-dev:
    build:
      context: .
      dockerfile: rss-scheduler/Dockerfile
      target: development
    container_name: rss-scheduler-dev
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - SERVICE_NAME=rss-scheduler
    volumes:
      # Mount source code for hot reloading
      - ./rss-scheduler:/app/rss-scheduler
      - ./shared:/app/shared
      - /app/rss-scheduler/node_modules # Anonymous volume for node_modules
      - /app/shared/node_modules
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - rss-network
    profiles:
      - dev

  rss-worker-dev:
    build:
      context: .
      dockerfile: rss-worker/Dockerfile
      target: development
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - SERVICE_NAME=rss-worker
    volumes:
      # Mount source code for hot reloading
      - ./rss-worker:/app/rss-worker
      - ./shared:/app/shared
      - /app/rss-worker/node_modules # Anonymous volume for node_modules
      - /app/shared/node_modules
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - rss-network
    profiles:
      - dev

  rss-api-dev:
    build:
      context: .
      dockerfile: rss-api/Dockerfile
      target: development
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - SERVICE_NAME=rss-api
    volumes:
      - ./rss-api:/app/rss-api
      - ./shared:/app/shared
      - /app/rss-api/node_modules # Anonymous volume for node_modules
      - /app/shared/node_modules
    depends_on:
      - redis
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - rss-network
    profiles:
      - dev

  redis:
    image: redis:7-alpine
    container_name: rss-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - rss-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - dev

volumes:
  redis_data:
    driver: local

networks:
  rss-network:
    driver: bridge
